name: Sync Upstream

on:
  # 每天UTC时间00:00自动运行（北京时间08:00）
  schedule:
    - cron: '0 0 * * *'
  
  # 也可以手动触发
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # 获取完整的git历史，以便能够正确合并
        fetch-depth: 0
        # 使用GitHub token进行认证
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Add upstream remote
      run: |
        git remote add upstream https://github.com/ycyy/Nano-Banana-Supermarket.git

    - name: Fetch upstream changes
      run: |
        git fetch upstream

    - name: Check for changes
      id: check_changes
      run: |
        # 检查上游是否有新的提交
        LOCAL=$(git rev-parse HEAD)
        REMOTE=$(git rev-parse upstream/main)
        if [ $LOCAL != $REMOTE ]; then
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "发现上游有新的更新"
        else
          echo "changes=false" >> $GITHUB_OUTPUT
          echo "上游没有新的更新"
        fi

    - name: Merge upstream changes
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        # 尝试自动合并上游的main分支
        git merge upstream/main --no-edit
        
    - name: Push changes
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git push origin main
        
    - name: Create Pull Request on conflict
      if: failure() && steps.check_changes.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: sync-upstream-${{ github.run_number }}
        title: "同步上游仓库更新"
        body: |
          这是一个自动生成的PR，用于同步上游仓库的更新。
          
          由于存在冲突，无法自动合并，请手动解决冲突后合并此PR。
          
          上游仓库: https://github.com/ycyy/Nano-Banana-Supermarket
        labels: |
          sync
          automated
